const cities = [
  { name: 'Chiang Mai', id: 'Chiang-Mai', country: 'Thailand', region: 'Southeast Asia' },
  { name: 'Bangkok', id: 'Bangkok', country: 'Thailand', region: 'Southeast Asia' },
  { name: 'Bali (Canggu)', id: 'Bali', country: 'Indonesia', region: 'Southeast Asia' },
  { name: 'Lisbon', id: 'Lisbon', country: 'Portugal', region: 'Europe' },
  { name: 'Porto', id: 'Porto', country: 'Portugal', region: 'Europe' },
  { name: 'Barcelona', id: 'Barcelona', country: 'Spain', region: 'Europe' },
  { name: 'Berlin', id: 'Berlin', country: 'Germany', region: 'Europe' },
  { name: 'Prague', id: 'Prague', country: 'Czech Republic', region: 'Europe' },
  { name: 'Budapest', id: 'Budapest', country: 'Hungary', region: 'Europe' },
  { name: 'Tbilisi', id: 'Tbilisi', country: 'Georgia', region: 'Europe' },
  { name: 'Medellín', id: 'Medellin', country: 'Colombia', region: 'Latin America' },
  { name: 'Mexico City', id: 'Mexico-City', country: 'Mexico', region: 'Latin America' },
  { name: 'Playa del Carmen', id: 'Playa-del-Carmen', country: 'Mexico', region: 'Latin America' },
  { name: 'Buenos Aires', id: 'Buenos-Aires', country: 'Argentina', region: 'Latin America' },
  { name: 'Lima', id: 'Lima', country: 'Peru', region: 'Latin America' },
  { name: 'Bogotá', id: 'Bogota', country: 'Colombia', region: 'Latin America' },
  { name: 'Ho Chi Minh City', id: 'Ho-Chi-Minh-City', country: 'Vietnam', region: 'Southeast Asia' },
  { name: 'Da Nang', id: 'Da-Nang', country: 'Vietnam', region: 'Southeast Asia' },
  { name: 'Kuala Lumpur', id: 'Kuala-Lumpur', country: 'Malaysia', region: 'Southeast Asia' },
  { name: 'Seoul', id: 'Seoul', country: 'South Korea', region: 'East Asia' },
  { name: 'Tokyo', id: 'Tokyo', country: 'Japan', region: 'East Asia' },
  { name: 'Taipei', id: 'Taipei', country: 'Taiwan', region: 'East Asia' },
  { name: 'Dubai', id: 'Dubai', country: 'United Arab Emirates', region: 'Middle East' },
  { name: 'Cape Town', id: 'Cape-Town', country: 'South Africa', region: 'Africa' },
  { name: 'Nairobi', id: 'Nairobi', country: 'Kenya', region: 'Africa' },
  { name: 'Marrakech', id: 'Marrakech', country: 'Morocco', region: 'Africa' },
  { name: 'Split', id: 'Split', country: 'Croatia', region: 'Europe' },
  { name: 'Athens', id: 'Athens', country: 'Greece', region: 'Europe' },
  { name: 'Bucharest', id: 'Bucharest', country: 'Romania', region: 'Europe' },
  { name: 'Sofia', id: 'Sofia', country: 'Bulgaria', region: 'Europe' },
  { name: 'Belgrade', id: 'Belgrade', country: 'Serbia', region: 'Europe' },
  { name: 'Tirana', id: 'Tirana', country: 'Albania', region: 'Europe' },
  { name: 'Las Palmas', id: 'Las-Palmas-de-Gran-Canaria', country: 'Spain', region: 'Europe' },
  { name: 'Florianopolis', id: 'Florianopolis', country: 'Brazil', region: 'Latin America' },
  { name: 'Austin', id: 'Austin', country: 'United States', region: 'North America' },
  { name: 'Denver', id: 'Denver', country: 'United States', region: 'North America' },
  { name: 'Miami', id: 'Miami', country: 'United States', region: 'North America' },
  { name: 'New York', id: 'New-York', country: 'United States', region: 'North America' },
  { name: 'London', id: 'London', country: 'United Kingdom', region: 'Europe' },
  { name: 'Amsterdam', id: 'Amsterdam', country: 'Netherlands', region: 'Europe' },
  { name: 'Paris', id: 'Paris', country: 'France', region: 'Europe' },
  { name: 'Singapore', id: 'Singapore', country: 'Singapore', region: 'Southeast Asia' }
];

console.log(cities.length);
